services:
  db:
    image: mysql:latest
    container_name: mysql_container
    env_file: .env
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - ~/mysql_data:/var/lib/mysql
    networks:
      - tomato-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  app:
    build: .
    container_name: app_container
    ports:
      - "8000:5000"
    env_file: .env
    environment:
      DATABASE_URL: mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db/${MYSQL_DATABASE}
    volumes:
      - ~/images:/app/static/img/products
    networks:
      - tomato-network
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

networks:
  tomato-network:
    driver: bridge

