"""add about prduct in History product model

Revision ID: 0b97856a7e33
Revises: 51d001ab1239
Create Date: 2024-10-09 12:37:02.153435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b97856a7e33'
down_revision = '51d001ab1239'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history_product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_product', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history_product', schema=None) as batch_op:
        batch_op.drop_column('about_product')

    # ### end Alembic commands ###
