"""udate history

Revision ID: 51d001ab1239
Revises: a4a75700ea21
Create Date: 2024-10-07 23:33:37.818644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51d001ab1239'
down_revision = 'a4a75700ea21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history_sales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('history_product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sales_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'history_sales', ['sales_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history_product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('sales_id')

    op.drop_table('history_sales')
    # ### end Alembic commands ###
