"""add: ing_link in Products

Revision ID: 5c84f44fb811
Revises: 3b5eb6cf8cc6
Create Date: 2024-09-16 17:00:16.130449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c84f44fb811'
down_revision = '3b5eb6cf8cc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_link', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('img_link')

    # ### end Alembic commands ###
