"""empty message

Revision ID: 72011cecc65e
Revises: 9de2af070378
Create Date: 2024-10-05 21:48:42.868026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72011cecc65e'
down_revision = '9de2af070378'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('about',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('about', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sell_and_by',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sell_and_by', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sell_and_by')
    op.drop_table('about')
    # ### end Alembic commands ###
